### ISSUE TITLE
[chapter7] meander radiusの値を増やすとpanicが発生する

### ISSUE THREAD

**Issue by gongqi-zhen** [gongqi-zhen/goblueprints#1]
radius : 10 APIから応答はあるがbodyはnil
radius : 100 以下のエラーが発生してmeander processが落ちる

```
% ./meander 
2021/06/03 10:22:25 serving meander API on :8080
2021/06/03 10:22:36 No places found for restaurant
2021/06/03 10:22:36 No places found for cafe
2021/06/03 10:22:36 No places found for casino
2021/06/03 10:22:36 No places found for bar

---meander 100
2021/06/03 10:22:59 No places found for casino
panic: reflect: reflect.Value.Set using value obtained using unexported field

goroutine 71 [running]:
reflect.flag.mustBeAssignableSlow(0x1d6)
        /usr/local/Cellar/go/1.16.3/libexec/src/reflect/value.go:257 +0x1b9
reflect.flag.mustBeAssignable(...)
        /usr/local/Cellar/go/1.16.3/libexec/src/reflect/value.go:247
reflect.Value.Set(0x129ba20, 0xc00016c640, 0x1d6, 0x129ba20, 0xc00011a290, 0x16)
        /usr/local/Cellar/go/1.16.3/libexec/src/reflect/value.go:1558 +0x3b
encoding/json.indirect(0x129ba20, 0xc00016c640, 0x1d6, 0x1587100, 0x18, 0xc000016240, 0x203000, 0x14edd60, 0x0, 0xc000189138, ...)
        /usr/local/Cellar/go/1.16.3/libexec/src/encoding/json/decode.go:472 +0x3f1
encoding/json.(*decodeState).object(0xc0002974c8, 0x129ba20, 0xc00016c640, 0x1d6, 0xc0002974f0, 0x7b)
        /usr/local/Cellar/go/1.16.3/libexec/src/encoding/json/decode.go:605 +0x65
encoding/json.(*decodeState).value(0xc0002974c8, 0x129ba20, 0xc00016c640, 0x1d6, 0x2, 0xc000124100)
        /usr/local/Cellar/go/1.16.3/libexec/src/encoding/json/decode.go:370 +0x6d
encoding/json.(*decodeState).object(0xc0002974c8, 0x12e5640, 0xc00016c640, 0x199, 0x13080d1, 0xb)
        /usr/local/Cellar/go/1.16.3/libexec/src/encoding/json/decode.go:765 +0x1325
encoding/json.(*decodeState).value(0xc0002974c8, 0x12e5640, 0xc00016c640, 0x199, 0x12e5640, 0xc00016c640)
        /usr/local/Cellar/go/1.16.3/libexec/src/encoding/json/decode.go:370 +0x6d
encoding/json.(*decodeState).array(0xc0002974c8, 0x12a28c0, 0xc000128240, 0x197, 0xc0002974f0, 0x5b)
        /usr/local/Cellar/go/1.16.3/libexec/src/encoding/json/decode.go:558 +0x1aa
encoding/json.(*decodeState).value(0xc0002974c8, 0x12a28c0, 0xc000128240, 0x197, 0x1, 0xc000122710)
        /usr/local/Cellar/go/1.16.3/libexec/src/encoding/json/decode.go:360 +0x105
encoding/json.(*decodeState).object(0xc0002974c8, 0x129bae0, 0xc000128240, 0x16, 0xc0002974f0, 0x7b)
        /usr/local/Cellar/go/1.16.3/libexec/src/encoding/json/decode.go:765 +0x1325
encoding/json.(*decodeState).value(0xc0002974c8, 0x129bae0, 0xc000128240, 0x16, 0xc000189b50, 0x10edd59)
        /usr/local/Cellar/go/1.16.3/libexec/src/encoding/json/decode.go:370 +0x6d
encoding/json.(*decodeState).unmarshal(0xc0002974c8, 0x129bae0, 0xc000128240, 0x0, 0x1)
        /usr/local/Cellar/go/1.16.3/libexec/src/encoding/json/decode.go:180 +0x1f4
encoding/json.(*Decoder).Decode(0xc0002974a0, 0x129bae0, 0xc000128240, 0x4be0f58, 0xc00006f500)
        /usr/local/Cellar/go/1.16.3/libexec/src/encoding/json/stream.go:73 +0x174
github.com/gongqi-zhen/goblueprints/chapter7/meander.(*Query).find(0xc00013e400, 0xc00011e040, 0x4, 0x0, 0x0, 0x0)
        /Users/makoto/GO/src/github.com/gongqi-zhen/goblueprints/chapter7/meander/query.go:70 +0x63a
github.com/gongqi-zhen/goblueprints/chapter7/meander.(*Query).Run.func1(0xc00011a100, 0xc00013e400, 0xc00011a0f8, 0xc00013e440, 0x4, 0x4, 0xc00011e040, 0x4, 0x0)
        /Users/makoto/GO/src/github.com/gongqi-zhen/goblueprints/chapter7/meander/query.go:86 +0x91
created by github.com/gongqi-zhen/goblueprints/chapter7/meander.(*Query).Run
        /Users/makoto/GO/src/github.com/gongqi-zhen/goblueprints/chapter7/meander/query.go:84 +0x1f2
meander % 
```

API keyをcurl等で利用すると値は取得できるので、プログラムに問題がある。

**Comment by gongqi-zhen** [comment]
https://developers.google.com/maps/documentation/places/web-service/photos

[]*googlePhotoの内容を確認する( URL )
```
type Place struct {
	*googleGeometry `json:"geometry"`
	Name            string         `json:"name"`
	Icon            string         `json:"icon"`
	Photos          []*googlePhoto `json:"photos"`
	Vicinity        string         `json:"vicinity"`
}
```

**Comment by gongqi-zhen** [comment]
```
makoto@miyazakimakotonoMacBook-Pro meander % curl -s -l "https://maps.googleapis.com/maps/api/place/nearbysearch/json?location=51.520707,-0.153809&radius=10&types=restaulant&minprice=0&macprice=5&key=APIKEY"
{
   "html_attributions" : [],
   "results" : [],
   "status" : "ZERO_RESULTS"
}
meander % 
```

```
meander % curl -s -l "https://maps.googleapis.com/maps/api/place/nearbysearch/json?location=51.520707,-0.153809&radius=50&types=restaulant&minprice=0&macprice=5&key=APIKEY" 
{
   "html_attributions" : [],
   "results" : [
      {
         "business_status" : "OPERATIONAL",
         "geometry" : {
            "location" : {
               "lat" : 51.52055439999999,
               "lng" : -0.1534758
            },
            "viewport" : {
               "northeast" : {
                  "lat" : 51.5219702302915,
                  "lng" : -0.152132419708498
               },
               "southwest" : {
                  "lat" : 51.5192722697085,
                  "lng" : -0.154830380291502
               }
            }
         },
         "icon" : "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/restaurant-71.png",
         "name" : "The Rajdoot",
         "opening_hours" : {
            "open_now" : false
         },
         "photos" : [
            {
               "height" : 1383,
               "html_attributions" : [
                  "\u003ca href=\"https://maps.google.com/maps/contrib/116176820826030337120\"\u003eThe Rajdoot\u003c/a\u003e"
               ],
               "photo_reference" : "ATtYBwL9t5i8podsUhnZ43ZjQt-6rUSY-p4MNK5J2qxOnjCA7AEuJSRcxLnaW0jynLqKt2gimnpL_0-oirS8qyw3CbzpsarUDLkmW27RR-dmcOy8SyLHwtc9gE9YMfESpnn_eCz12Fqf_U0Ohlrh5-kL-coL7xIr38s6VaCJwr8Scko7oWXu",
               "width" : 1566
            }
         ],
         "place_id" : "ChIJHR-PBc4adkgRyVQ45tws_Iw",
         "plus_code" : {
            "compound_code" : "GRCW+6J London, UK",
            "global_code" : "9C3XGRCW+6J"
         },
         "price_level" : 2,
         "rating" : 4.4,
         "reference" : "ChIJHR-PBc4adkgRyVQ45tws_Iw",
         "scope" : "GOOGLE",
         "types" : [
            "meal_takeaway",
            "restaurant",
            "food",
            "point_of_interest",
            "establishment"
         ],
         "user_ratings_total" : 800,
         "vicinity" : "49 Paddington Street, London"
      },
      {
         "business_status" : "OPERATIONAL",
         "geometry" : {
            "location" : {
               "lat" : 51.5205722,
               "lng" : -0.1533264
            },
            "viewport" : {
               "northeast" : {
                  "lat" : 51.52198258029149,
                  "lng" : -0.151984969708498
               },
               "southwest" : {
                  "lat" : 51.51928461970849,
                  "lng" : -0.154682930291502
               }
            }
         },
         "icon" : "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/restaurant-71.png",
         "name" : "Bombay Spice - Marylebone Indian restaurant - Marylebone restaurants",
         "opening_hours" : {
            "open_now" : false
         },
         "photos" : [
            {
               "height" : 2202,
               "html_attributions" : [
                  "\u003ca href=\"https://maps.google.com/maps/contrib/111026879282307368119\"\u003ePepe Amengual\u003c/a\u003e"
               ],
               "photo_reference" : "ATtYBwIZxjGak4t5VQbnda7GWEECV5MlH8n8PhdW1wYgMraRX4K1xXO3Xa1XIzkL1t8FtLcnu8H_wOsyZJPrwUjJ5B6M4IzDMwaCxcpUpjOUjkGvpXos97DGZoG0LrZB8kFBzJzg_1LMCz4zacwv2fzps_Bvr_QNfb72TRLAY-OsvScyd7wx",
               "width" : 2934
            }
         ],
         "place_id" : "ChIJ32W7Bc4adkgRkKOH1oXf07Q",
         "plus_code" : {
            "compound_code" : "GRCW+6M London, UK",
            "global_code" : "9C3XGRCW+6M"
         },
         "price_level" : 2,
         "rating" : 3.5,
         "reference" : "ChIJ32W7Bc4adkgRkKOH1oXf07Q",
         "scope" : "GOOGLE",
         "types" : [
            "meal_takeaway",
            "bar",
            "restaurant",
            "food",
            "point_of_interest",
            "establishment"
         ],
         "user_ratings_total" : 282,
         "vicinity" : "50 Paddington Street, London"
      }
   ],
   "status" : "OK"
}
meander % 
```

**Comment by gongqi-zhen** [comment]
> ToDo: json-to-goの結果と、現行の構造体を確認する。

以下のcommitで修正

https://github.com/gongqi-zhen/goblueprints/commit/984b9d7190013a18f213455da26fb009249e35b4
